import type { Metadata } from "next";
import { Poppins, Instrument_Sans } from "next/font/google";
import "@/app/globals.css";

import Footer from "@/components/Footer";
import Image from "next/image";
import Link from "next/link";
import { Student } from "@phosphor-icons/react/dist/ssr";
import Logout from "@/components/Logout";

const poppins = Poppins({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], variable: "--font-p" });

const instrumentSans = Instrument_Sans({ subsets: ["latin"], weight: ["400", "500", "600", "700"], variable: "--font-is" });

export const metadata: Metadata = {
	title: "Al-Alusi Portal",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html>
			<body className={`${poppins.variable} ${instrumentSans.variable} antialiased bg-off-white`}>
				<div className="min-h-screen flex flex-col">

					<section className="grid grid-cols-5 grid-flow-row gap-4 p-3 flex-grow">
						<aside className="flex flex-col items-center h-full gap-4 bg-white p-4 border border-gray-200 rounded-lg">
							<div className="flex flex-col items-center gap-4 flex-grow">
								<div className="flex flex-row items-center gap-1">
									<Image src="/logo.png" alt="" width={55} height={55} />
									<h4>
										<Link href="/" className="hidden lg:block font-semibold text-black">
											Al-Alusi Portal
										</Link>
									</h4>
								</div>
								<ul className="w-full space-y-3 text-black ">
									<li className="flex flex-row items-center gap-3 rounded-xs py-1 px-1.5  hover:bg-off-white hover:border-1 hover:rounded-sm">
										<Student size={24} className="text-black" />
										<Link href={"/student-application"} className="w-full text-left">
											Student Application
										</Link>
									</li>
								</ul>
							</div>
							<div>
								<Logout />
							</div>
							
						</aside>
						{children}
					</section>
					<Footer />

				</div>
			</body>
		</html>
	);
}
