import type { Metadata } from "next";
import Footer from "@/components/Footer";
import Image from "next/image";
import Link from "next/link";
import { Users, Newspaper } from "@phosphor-icons/react/dist/ssr";

export const metadata: Metadata = {
	title: "Admin Dashboard",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<>
			<section className="grid grid-cols-5 grid-flow-row gap-4 p-3 h-[90vh]">
				<aside className="flex flex-col items-center h-full gap-4 bg-white p-4 border border-gray-200 rounded-lg">
					<div className="flex flex-row items-center gap-1">
						<Image src="/logo.jpg" alt="" width={55} height={55} />
						<h4>
							<Link href="/" className="hidden lg:block font-semibold text-black">
								Al-Alusi Portal
							</Link>
						</h4>
					</div>

					<ul className="w-full space-y-3 text-black ">
						<li className="flex flex-row items-center gap-3 rounded-xs py-1 px-1.5  hover:bg-light-gray">
							<Newspaper size={24} className="text-black" />
							<Link href={"/admin/dashboard/newsfeed"} className="w-full text-left">
								Newsfeed Management
							</Link>
						</li>
						<li className="flex flex-row items-center gap-3 rounded-xs py-1 px-1.5  hover:bg-light-gray">
							<Users size={24} className="text-black" />
							<Link href={"/admin/dashboard/newsfeed"} className="w-full text-left">
								User Management
							</Link>
						</li>
					</ul>
				</aside>
				{children}
			</section>
			<Footer />
		</>
	);
}
