import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import { Poppins, Instrument_Sans } from "next/font/google";
import "@/app/globals.css";

import Footer from "@/components/Footer";

const poppins = Poppins({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], variable: "--font-p" });

const instrumentSans = Instrument_Sans({ subsets: ["latin"], weight: ["400", "500", "600", "700"], variable: "--font-is" });

export const metadata: Metadata = {
	title: "Al-Alusi Portal",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${poppins.variable} ${instrumentSans.variable} antialiased bg-off-white`}>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
